name: social_network_mate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  pdf: ^3.10.4
  riverpod_annotation: ^2.1.5
  slang: ^3.24.0
  slang_flutter: ^3.24.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  json_serializable: ^6.7.1
  slang_build_runner: ^3.24.0

flutter:
  uses-material-design: true
